### ISSUE TITLE
doesn't compile when rtttl is added to config

### ISSUE THREAD

**Issue by kiddyfurby** [olicooper/esphome-nspanel-lovelace-native#12]
`undefined reference to esphome::output::FloatOutput::set_zero_means_zero(bool)` when using ledc 
```
output:
  ## Buzzer for playing tones
  - platform: ledc
    id: buzzer_out
    pin: 21

## Rtttl function for buzzer
rtttl:
  id: buzzer
  output: buzzer_out
```
