### ISSUE TITLE
Build script gets confused if you use external_components source: git

### ISSUE THREAD

**Issue by CultusMechanicus** [olicooper/esphome-nspanel-lovelace-native#2]
I thought I'd simplify my builds by using

```
external_components:
  - source:
      type: git
      url: https://github.com/olicooper/esphome-nspanel-lovelace-native
      ref: dev
    components: [ nspanel-lovelace]
```

However, whatever the build path this uses doesn't get handled by __init.py properly, and the build fails on the first include (icons.json, iirc).

Not a biggie, I just checked the repo out manually and included it as a local external component, but it would simplify updating to new versions if it worked.
