### ISSUE TITLE
daylight saving time

### ISSUE THREAD

**Issue by kiddyfurby** [olicooper/esphome-nspanel-lovelace-native#3]
First of all, I LOVE the speed!!! Now I am refreshing the project page a couple of times a day waiting for cardThermo!

OOTB, esphome's auto detection of timezone failed, thus the screensaver screen showed the winter time.

As a workaround, add timezone param to time: config
```
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/London
```

Any chance we could add a note to the example config?
