### ISSUE TITLE
[FeatureRequest] Display auto off

### ISSUE THREAD

**Issue by andreas-bulling** [olicooper/esphome-nspanel-lovelace-native#31]
It would be nice to have a configurable display auto off functionality, i.e. a setting (ideally changeable through HA) that defines after how many seconds the display turns off.

**Comment by olicooper** [comment]
I haven't really tested it properly, but you can probably call the `set_display_dim` function using an [action](https://esphome.io/components/api#user-defined-actions) (used the be called a `service call`) or [template button](https://esphome.io/components/button/template) press?
The [advanced_example.yaml](https://github.com/olicooper/esphome-nspanel-lovelace-native/blob/a5f2ddeb0f999e7b3e2974a753cfda4b8f9643f1/advanced-example.yaml#L177-L178) provides some hints on how to configure it but it is like this:
```yaml

api:
  actions:
    ## Action to set the the display dim level HA
    ## note: make sure inactive_level < active_level and both values are between 0 and 100 !
    - action: set_display_dim
      variables:
        inactive_level: int
        active_level: int
      then:
        - lambda: 'id(nspanel).set_display_dim(inactive_level, active_level);'
```

You could also create an esphome automation if you need it to automatically turn back off after a period of time but you'll need to look through the esphome documentation to work out how to do that.
I hope that helps! 😃
