### ISSUE TITLE
Weather hourly forecast doesn't apply timezone

### ISSUE THREAD

**Issue by mmorev** [olicooper/esphome-nspanel-lovelace-native#35]
Hello! Very cool project, performance is awesome, thanks!

I have configured hourly forecast, and it shows time in UTC, not in my timezone (UTC+6 Asia/Omsk). Here is forecast sensor data:

```
temperature: 3.1
temperature_unit: °C
forecast: 
- datetime: '2025-03-22T15:00:00+06:00'
  is_daytime: true
  condition: sunny
  wind_bearing: 225
  wind_bearing_label: sw
  precipitation_type: none
  precipitation_intensity: none
  uv_index: 2
  temperature: 2
  apparent_temperature: -5.3
  pressure: 760
  wind_gust_speed: 6
  wind_speed: 6
  precipitation: 0
  humidity: 48
- datetime: '2025-03-22T18:00:00+06:00'
  is_daytime: true
  condition: sunny
  wind_bearing: 225
  wind_bearing_label: sw
  precipitation_type: none
  precipitation_intensity: none
  uv_index: 2
  temperature: 1
  apparent_temperature: -5.6
  pressure: 759
  wind_gust_speed: 5
  wind_speed: 5
  precipitation: 0
  humidity: 52
- datetime: '2025-03-22T21:00:00+06:00'
  is_daytime: true
  condition: partlycloudy
  wind_bearing: 180
  wind_bearing_label: s
  precipitation_type: none
  precipitation_intensity: none
  uv_index: 2
  temperature: 0
  apparent_temperature: -5.6
  pressure: 758
  wind_gust_speed: 4
  wind_speed: 4
  precipitation: 0
  humidity: 66
- datetime: '2025-03-23T00:00:00+06:00'
  is_daytime: false
  condition: partlycloudy
  wind_bearing: 225
  wind_bearing_label: sw
  precipitation_type: none
  precipitation_intensity: none
  uv_index: 3
  temperature: 0
  apparent_temperature: -6.3
  pressure: 756
  wind_gust_speed: 5
  wind_speed: 5
  precipitation: 0
  humidity: 66
- datetime: '2025-03-23T03:00:00+06:00'
  is_daytime: false
  condition: snowy
  wind_bearing: 225
  wind_bearing_label: sw
  precipitation_type: snow
  precipitation_intensity: small
  uv_index: 3
  temperature: 0
  apparent_temperature: -6.1
  pressure: 754
  wind_gust_speed: 5
  wind_speed: 5
  precipitation: 0.2
  humidity: 76
- datetime: '2025-03-23T06:00:00+06:00'
  is_daytime: false
  condition: snowy
  wind_bearing: 0
  wind_bearing_label: 'n'
  precipitation_type: snow
  precipitation_intensity: small
  uv_index: 3
  temperature: -2
  apparent_temperature: -7.7
  pressure: 755
  wind_gust_speed: 4
  wind_speed: 4
  precipitation: 0.8
  humidity: 76
- datetime: '2025-03-23T09:00:00+06:00'
  is_daytime: false
  condition: partlycloudy
  wind_bearing: 315
  wind_bearing_label: nw
  precipitation_type: none
  precipitation_intensity: none
  uv_index: 3
  temperature: -3
  apparent_temperature: -8.3
  pressure: 755
  wind_gust_speed: 3
  wind_speed: 3
  precipitation: 0
  humidity: 63
- datetime: '2025-03-23T12:00:00+06:00'
  is_daytime: false
  condition: clear-night
  wind_bearing: 270
  wind_bearing_label: w
  precipitation_type: none
  precipitation_intensity: none
  uv_index: 3
  temperature: 0
  apparent_temperature: -7.4
  pressure: 754
  wind_gust_speed: 6
  wind_speed: 6
  precipitation: 0
  humidity: 51
- datetime: '2025-03-23T15:00:00+06:00'
  is_daytime: true
  condition: sunny
  wind_bearing: 225
  wind_bearing_label: sw
  precipitation_type: none
  precipitation_intensity: none
  uv_index: 3
  temperature: 1
  apparent_temperature: -7.9
  pressure: 752
  wind_gust_speed: 8
  wind_speed: 8
  precipitation: 0
  humidity: 43
- datetime: '2025-03-23T18:00:00+06:00'
  is_daytime: true
  condition: sunny
  wind_bearing: 225
  wind_bearing_label: sw
  precipitation_type: none
  precipitation_intensity: none
  uv_index: 3
  temperature: 1
  apparent_temperature: -7.8
  pressure: 750
  wind_gust_speed: 8
  wind_speed: 8
  precipitation: 0
  humidity: 48
- datetime: '2025-03-23T21:00:00+06:00'
  is_daytime: true
  condition: partlycloudy
  wind_bearing: 270
  wind_bearing_label: w
  precipitation_type: none
  precipitation_intensity: none
  uv_index: 3
  temperature: 1
  apparent_temperature: -6.8
  pressure: 748
  wind_gust_speed: 7
  wind_speed: 7
  precipitation: 0
  humidity: 59
```

And here is the panel weather update log:

```
[16:17:00][D][nspanel_lovelace:1265]: TFT CMD OUT: weatherUpdate~~~~38066~~3.1°C~~~~65504~09:00~2.0°C~~~~65504~12:00~1.0°C~~~~38066~15:00~0.0°C~~~~38066~18:00~0.0°C
```

The first 4 items have timestamps with TZ +06:00:
```
datetime: '2025-03-22T15:00:00+06:00'
datetime: '2025-03-22T18:00:00+06:00'
datetime: '2025-03-22T21:00:00+06:00'
datetime: '2025-03-23T00:00:00+06:00'

```
But these items display as UTC+0. Current time (above date) on main screen displays correctly.

![Image](https://github.com/user-attachments/assets/2d511a85-dfa0-4102-88ff-bc6b21bc3eeb)

My config file:
```yaml
...
nspanel_lovelace:
  id: nspanel
  screensaver:
    time_id: homeassistant_time
    weather:
      entity_id: sensor.weather_forecast_hourly
...
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Asia/Omsk
```

By the way, my forecast source always has the first item in the past, could you implement a flag to skip first N items from forecast, or any items which have timestamp in the past? In my original Lovelace UI config i used to set specific items starting from 1, like:
```
    screensaver:
      entities:
        - entity: weather.gismeteo
# first item is skipped
#        - entity: sensor.weather_forecast_hourly
#          type: 0
        - entity: sensor.weather_forecast_hourly
          type: 1
        - entity: sensor.weather_forecast_hourly
          type: 2
        - entity: sensor.weather_forecast_hourly
          type: 3
        - entity: sensor.weather_forecast_hourly
          type: 4
```
This is not possible using current implementation.

Hope you can fix this. Thanks in advance!
