### ISSUE TITLE
Weather forecast not loading after reboot

### ISSUE THREAD

**Issue by mmorev** [olicooper/esphome-nspanel-lovelace-native#36]
Hello! After power cycling, weather forecast could not be loaded until templated sensor update occurs.

So it looks like this:

![Image](https://github.com/user-attachments/assets/6ad3ac4c-18a4-44c2-b5bc-d2ccb496dd60)

Here is the panel log after boot or on return to main screen (by timeout):
```
[16:51:28][D][nspanel_lovelace:1265]: TFT CMD OUT: weatherUpdate~~~~38066~~3.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C
```

Forecast appears immediately if I force update HA templates from Develooper menu:

```
53:00][D][nspanel_lovelace:1265]: TFT CMD OUT: time~16:53
[16:53:03][D][nspanel_lovelace:1265]: TFT CMD OUT: weatherUpdate~~~~38066~~3.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C
[16:53:03][D][nspanel_lovelace:1265]: TFT CMD OUT: weatherUpdate~~~~38066~~3.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C
[16:53:03][D][nspanel_lovelace:1265]: TFT CMD OUT: weatherUpdate~~~~38066~~3.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C
[16:53:03][D][nspanel_lovelace:1265]: TFT CMD OUT: weatherUpdate~~~~38066~~3.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C~~~~63878~~0.0°C
# Immediately after templates update:
[16:53:03][D][nspanel_lovelace:1265]: TFT CMD OUT: weatherUpdate~~~~38066~~3.0°C~~~~65504~09:00~2.0°C~~~~65504~12:00~1.0°C~~~~38066~15:00~0.0°C~~~~31728~18:00~0.0°C
```

Here is my panel config:
```
...
nspanel_lovelace:
  id: nspanel
  screensaver:
    time_id: homeassistant_time
    weather:
      entity_id: !secret weather_entity_id
...
```

And HA forecast template config:
```
- trigger:
    - platform: time_pattern
      minutes: /15
    - platform: homeassistant
      event: start
    - platform: event
      event_type: event_template_reloaded
  action:
    - service: weather.get_forecasts
      data:
        type: hourly
      target:
        entity_id: weather.gismeteo
      response_variable: hourly
  sensor:
    - name: Weather Forecast Hourly
      unique_id: weather_forecast_hourly
      state: "{{ states('weather.gismeteo') }}"
      attributes:
        temperature: "{{ state_attr('weather.gismeteo', 'temperature') }}"
        temperature_unit: "{{ state_attr('weather.gismeteo', 'temperature_unit') }}"
        forecast: >
                [{%- for n in hourly['weather.gismeteo'].forecast  %}
                   {
                   {%- for k, v in n.items() %}
                     {%- if v is datetime %}
                     "{{ k }}": "{{ v.isoformat() }}",
                     {%- elif v is string %}
                     "{{ k }}": "{{ v }}",
                     {%- else %}
                     "{{ k }}": {{ v }},
                     {%- endif %}
                   {%- endfor %}
                   },
                 {%- endfor %}]

```

Did I misconfigured something?

**Comment by olicooper** [comment]
Nothing stands out to me initially. The nspanel subscribes to updates from HA, so when it connects it should get the latest state automatically. It looks like it is not getting the initial state but I don't know why. You might be able to see more info if you connect the nspanel with a serial cable so you can see the logs when it is connecting to wifi and subscribing to entity updates which might shed some light on what is happening?
You could also try updating your config to make it similar to the sample config to see if something is misconfigured?
Is the entity_id in your nspanel config set to `sensor.weather_forecast_hourly` to match your HA template config?

This won't fix anything but another small thing you could add to your HA template config is limiting how many forecast items are included to reduce nspanel memory consumption.
```python
# From this
[{%- for n in hourly['weather.gismeteo'].forecast  %}

# To something like this
[{%- for n in hourly['weather.gismeteo'].forecast[0:5]  %}```

**Comment by Chreece** [comment]
Did this brake something?:
https://github.com/joBr99/nspanel-lovelace-ui/releases/tag/v4.7.2

I can only see current temperature and not forecast

**Comment by olicooper** [comment]
@Chreece No, I don't use any code from that repository besides the [HMI display code](https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI) which was last updated 8 months ago, so I suspect that there might have been a Home Assistant or esphome update that broke it or the forecast data is wrong? Have you updated either of those recently? Can you check what your HA weather entity state is - does it contain the forecast data still?

**Comment by Chreece** [comment]
Hey @olicooper, yes I am always using the latest version of HA and esphome (currently 2025.7.x). My weather entities do still contain the forecast (I'm using the weather.get_forecasts service for my entity).
Don't you have this problem?

**Comment by Chreece** [comment]
Here are the attributes of my entity:
```
temperature: 20.4
temperature_unit: °C
forecast:
  - datetime: "2025-07-22T17:00:00Z"
    cloud_coverage: 72
    condition: pouring
    precipitation_probability: null
    pressure: 1011.2
    uv_index: 5
    wind_gust_speed: 35.2
    wind_bearing: 245
    temperature: 20.4
    dew_point: 14.2
    wind_speed: 20.4
    precipitation: 0.3
  - datetime: "2025-07-22T18:00:00Z"
    cloud_coverage: 73
    condition: pouring
    precipitation_probability: null
    pressure: 1011.6
    uv_index: 5
    wind_gust_speed: 29.6
    wind_bearing: 241
    temperature: 19.9
    dew_point: 14.2
    wind_speed: 16.7
    precipitation: 0.2
  - datetime: "2025-07-22T19:00:00Z"
    cloud_coverage: 73
    condition: pouring
    precipitation_probability: null
    pressure: 1012.1
    uv_index: 5
    wind_gust_speed: 25.9
    wind_bearing: 239
    temperature: 19.3
    dew_point: 14.4
    wind_speed: 14.8
    precipitation: 0.3
  - datetime: "2025-07-22T20:00:00Z"
    cloud_coverage: 74
    condition: rainy
    precipitation_probability: null
    pressure: 1012.5
    uv_index: 5
    wind_gust_speed: 22.2
    wind_bearing: 235
    temperature: 18.6
    dew_point: 14.4
    wind_speed: 13
    precipitation: 0.3
  - datetime: "2025-07-22T21:00:00Z"
    cloud_coverage: 73
    condition: pouring
    precipitation_probability: null
    pressure: 1012.8
    uv_index: 5
    wind_gust_speed: 22.2
    wind_bearing: 230
    temperature: 18.1
    dew_point: 14.4
    wind_speed: 13
    precipitation: 0.2
friendly_name: Weather Forecast Hourly
```
Every time i update a string of the forecast items i'm getting:
`Weather unparsable: InvalidInput`

**Comment by olicooper** [comment]
> `Weather unparsable: InvalidInput`
That is interesting and suggests that it is Home Assistant which could be the issue (or the esphome integration on HA).

I don't update my panel very often so I haven't noticed this issue, but I've just updated to esphome version `2025.7.2` and everything is still working for me.
My weather entity has the same structure to yours so something is going wrong with the communication of the data between HA and the panel. I am on HA version `2025.5.3` so the next thing I can do is update HA.

**Comment by olicooper** [comment]
@mmorev I have looked at your template and I can see that there was trailing commas on your JSON which was making it invalid.

I have spent some time making a more tailored template which filters out all attributes that are not required by the panel and formats the date as local (remove that if you want)...

```yaml
{%- with ns = namespace(arr=[],obj={}) -%}
{%- for n in hourly['weather.gismeteo'].forecast[:5] -%}
  {%- for k, v in n | items -%}
    {%- if k == "datetime" -%}
      {%- set ns.obj = dict(ns.obj | items, **{k: as_datetime(v, "0" | as_datetime) | as_local | as_timestamp | timestamp_custom('%Y-%m-%dT%H:%M:%S')}) -%}
    {%- elif k == "condition" or k == "temperature" -%}
      {%- set ns.obj = dict(ns.obj | items, **{k: v}) -%}
    {%- endif -%}
  {%- endfor -%}
  {%- if (ns.obj.items() | length) == 3 and ns.obj.datetime -%}
    {%- set ns.arr = ns.arr + [ns.obj] -%}
  {%- endif -%}
{%- endfor %}{{ns.arr | to_json}}{% endwith %}
```

I will add the updated template to the readme

**Comment by olicooper** [comment]
@Chreece I've updated my HA version to `2025.7.3` but it is still working for me.. Could you try the new template and check the entity state looks similar to this:
```yaml
temperature: 20
temperature_unit: °C
forecast:
  - datetime: "2025-07-24T00:00:00"
    condition: sunny
    temperature: 22
  - datetime: "2025-07-25T00:00:00"
    condition: cloudy
    temperature: 16
  - datetime: "2025-07-26T00:00:00"
    condition: cloudy
    temperature: 12
  - datetime: "2025-07-27T00:00:00"
    condition: sunny
    temperature: 14
  - datetime: "2025-07-28T00:00:00"
    condition: sunny
    temperature: 15
friendly_name: Weather Forecast Daily
```

**Comment by Chreece** [comment]
Thanks @olicooper. I changed in developer tools the attributes of my sensor, to leave only the datetime, condition and temperature. That worked!
~~So something in the original attributes is messing with the code! Could that be the "null" on the precipitation_probability, or there are too many keys in the items of the list?~~

Edit:
Yes, my original sensor has 12 items and removing the precipitation_probability keys is successfully parsed by nspanel

**Comment by olicooper** [comment]
That is great to hear. Yes, it could have been the null values (but values that are not required should have been filtered out when the update first arrives), or the JSON string is invalid for another reason? I have added a debug log so you can see what JSON the nspanel receives when an update arrives and errors with `Weather unparsable: InvalidInput` which might help to understand the problem. The error is coming from the ArduinoJson library.

It is best to reduce the size of data sent to the display if possible, could you update your HA template to be similar to the one on the [homepage readme](https://github.com/olicooper/esphome-nspanel-lovelace-native/blob/dev/README.md#1-weather-forecast-is-not-displayed-on-the-screensaver-when-using-home-assistant-20244-or-later)? That will reduce the data and remove those null values automatically.

**Comment by Chreece** [comment]
Because I'm using this sensor also for other purposes I'm not happy to remove keys.
I will create a new one to remove the null key values.
If you want to test the reasons why it doesn't parse keys with null value you could paste the values from my sensor from above in your developer tools in HA.

Edit:
I changed a bit your template to reject any keys with null values:
```
{%- with ns = namespace(arr=[],obj={}) -%}
  {%- for n in hourly[entity_id].forecast[:12] -%}
    {%- for k, v in n | items -%}
      {%- if k == "datetime" -%}
        {%- set ns.obj = dict(ns.obj | items, **{k: as_datetime(v, "0" | as_datetime) | as_local | as_timestamp | timestamp_custom('%Y-%m-%dT%H:%M:%S')}) -%}
      {%- elif v not in [null, none] -%}
        {%- set ns.obj = dict(ns.obj | items, **{k: v}) -%}
      {%- endif -%}
    {%- endfor -%}
    {%- set ns.arr = ns.arr + [ns.obj] -%}
  {%- endfor %}
    {{ns.arr | to_json}}
{% endwith %}
```

**Comment by olicooper** [comment]
So I tried your sensor data and the `null` value is being converted to `None` (Pythons version of null) and you can see all the keys use single quotes instead of double quotes, which means HA is sending python objects rather than JSON to the panel. This needs correcting before it reaches the panel so I will have a look for any reports of this issue in HA and esphome.

In regards to your template modifications, they are fine, but it is better to remove all keys that are not required if possible and given what I've just found out I am surprised that the invalid (not JSON) data is being parsed at all!

It is possible to create more than one sensor within the same template and use the new one just for your panel to reduce the chance of other issues appearing in the future e.g.

```yaml
    sensor:
      - name: Weather Forecast Daily
        unique_id: weather_forecast_daily
        state: ...
    sensor:
      - name: Weather Forecast Daily (NSPanel)
        unique_id: weather_forecast_daily_nspanel
        state: ...
```
You can even be change the visibility in HA so it doesn't bother you (this is also advice for anyone looking at this in the future).

Thanks for helping to test! 👍
