### ISSUE TITLE
discussion: esp-idf options

### ISSUE THREAD

**Issue by kiddyfurby** [olicooper/esphome-nspanel-lovelace-native#38]
NOT AN ISSUE, but seeing discussion is not enabled on this repo, allow me...

I'd really love to have bluetooth_proxy working (so that my nspanels around the home can track my devices via [bermuda](https://github.com/agittins/bermuda)

But simply enabling bluetooth_proxy resulted in an unresponsive nspanel (luckily OTA is still available)
Seeing that they got bluetooth -Proxy working, I copied over the sdk option from [NSPanel_HA_Blueprint](https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/0c0be2dd26ee12de5d30628c60940976b9ce40f8/components/nspanel_ha_blueprint/__init__.py#L33)
And I am happy to report we can get bluetooth_proxy working onesphome-nspanel-lovelace-native as of esphome 2025.3

Here's the yaml:
```
esp32:
  board: esp32dev
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_D0WD_PSRAM_CLK_IO: "5"
      CONFIG_D0WD_PSRAM_CS_IO: "18"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_ESP32_REV_MIN_3: "y"
      CONFIG_MBEDTLS_DYNAMIC_BUFFER: "y"
      CONFIG_MBEDTLS_DYNAMIC_FREE_CA_CERT: "y"
      CONFIG_MBEDTLS_DYNAMIC_FREE_CONFIG_DATA: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY: "y"
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
```

I tried having only CONFIG_D0WD_PSRAM_CLK_IO / CONFIG_D0WD_PSRAM_CS_IO without the other options and it won't work.
I also remember earlier in this project we used to have those CONFIG_D0WD_PSRAM_CLK_IO lines but they are now removed from the sample config.
