### ISSUE TITLE
Weather on screensaver tries to read the 'forecast' attribute on weather entities, which has been removed from HA recently.

### ISSUE THREAD

**Issue by CultusMechanicus** [olicooper/esphome-nspanel-lovelace-native#8]
Not really an issue, but you need to point the screensaver weather at a template sensor like the one below as HA 2024.04 removed the 'forecast' attribute out to a service call for some random reason...
```
template:
  - trigger:
      - platform: time_pattern
        hours: /1
      - platform: homeassistant
        event: start
    action:
      - service: weather.get_forecasts
        data:
          type: daily
        target:
          entity_id: weather.home # change to your weather entity
        response_variable: daily
    sensor:
      - name: Weather Forecast Daily
        unique_id: weather_forecast_daily
        state: "{{ states('weather.home') }}" # # change to your weather entity in this line
        attributes:
          temperature: "{{ state_attr('weather.home', 'temperature') }}" # change to your weather entity
          temperature_unit: "{{ state_attr('weather.home', 'temperature_unit') }}" # change to your weather entity
          forecast: "{{ daily['weather.home'].forecast }}" # change to your weather entity
```

**Comment by olicooper** [comment]
Interesting! This change shouldn't be too hard to make, but I will lose the automatic status updates so I might have to poll the service instead now. I am on HA v4.3 so that explains why I haven't spotted this yet. Thankfully the weather service is already included in v4.3.

**Comment by CultusMechanicus** [comment]
Yeah, I don't quite get the reasoning they had when they moved it from an attribute on weather entities to a service call, it broke a lot of things.

**Comment by olicooper** [comment]
Unfortunately esphome does not support service calls with response data so I have submitted a feature request https://github.com/esphome/feature-requests/issues/2703

**Comment by andreas-bulling** [comment]
I have tried this solution but encountered a problem. The template sensor works in principle but it mixes up days and forecasts: Today's temperature and forecast are shown on the far left, slightly enlarged. As it should be.

Right next to it, however, it shows the previous day (Saturday, as I am writing this on a Sunday) but with the forecast for Monday. And so on. So the labels are shifted by two days.

![IMG_20250105_172745_956](https://github.com/user-attachments/assets/b9bc84ba-99c3-4506-b23d-a1a98f31f618)

**Comment by olicooper** [comment]
The screen just reads the JSON data that is sent to it, so it is likely that your weather provider has the previous days weather as the first element in the array.. Have a look at the sensor state in developer tools on Home Assistant to confirm this. I think I have seen similar with my setup but after midday it refreshes to show the next day. The first (larger) icon is the 'current' weather taken from the main weather `state` and `temperature` attribute.

There might be a bug too so I will double check this but you should be able to correlate the sensor data with what you see on the screen. I would imagine you will be able to adjust what data is provided by adjusting the config in HA.

**Comment by andreas-bulling** [comment]
I will try once the display works again. It was working fine yesterday but after switching it off over night (given it doesn't have an auto-off function out of the box) it doesn't start up anymore today :(

**Comment by andreas-bulling** [comment]
This is what the template sensor `weather_forecast_daily` contains. The first entry is today's weather, the second is tomorrow's, and so on. Looks good to me, doesn't it?!

```
temperature: 10.4
temperature_unit: °C
forecast:
  - datetime: "2025-01-06T00:00:00Z"
    cloud_coverage: 96
    condition: rainy
    evaporation: null
    fog_probability: null
    precipitation_duration: 7500
    precipitation_probability: 53
    pressure: 1002.7
    sun_duration: 360
    sun_irradiance: 30
    uv_index: null
    visibility: 57200
    wind_gust_speed: 35.2
    wind_bearing: SW
    temperature: 12
    templow: 7
    dew_point: 4
    wind_speed: 16.7
    precipitation: 0.9
  - datetime: "2025-01-07T00:00:00Z"
    cloud_coverage: 96
    condition: cloudy
    evaporation: null
    fog_probability: 1
    precipitation_duration: 6660
    precipitation_probability: 32
    pressure: 1008.9
    sun_duration: 8100
    sun_irradiance: 2400
    uv_index: null
    visibility: 53400
    wind_gust_speed: 44.5
    wind_bearing: SW
    temperature: 7
    templow: 3
    dew_point: 3
    wind_speed: 22.2
    precipitation: 0
  - datetime: "2025-01-08T00:00:00Z"
    cloud_coverage: 100
    condition: rainy
    evaporation: 0.5
    fog_probability: 5
    precipitation_duration: 53400
    precipitation_probability: 77
    pressure: 1008.8
    sun_duration: 60
    sun_irradiance: 1070
    uv_index: null
    visibility: 6200
    wind_gust_speed: 24.1
    wind_bearing: S
    temperature: 6
    templow: 1
    dew_point: 5
    wind_speed: 11.1
    precipitation: 13
  - datetime: "2025-01-09T00:00:00Z"
    cloud_coverage: 100
    condition: snowy-rainy
    evaporation: 0.1
    fog_probability: 5
    precipitation_duration: 32520
    precipitation_probability: 70
    pressure: 1015.6
    sun_duration: 480
    sun_irradiance: 1160
    uv_index: null
    visibility: 7500
    wind_gust_speed: 40.8
    wind_bearing: SW
    temperature: 10
    templow: 2
    dew_point: 5
    wind_speed: 20.4
    precipitation: 7.9
  - datetime: "2025-01-10T00:00:00Z"
    cloud_coverage: 92
    condition: cloudy
    evaporation: 0.5
    fog_probability: 2
    precipitation_duration: 10740
    precipitation_probability: 52
    pressure: 1022.3
    sun_duration: 6180
    sun_irradiance: 2750
    uv_index: null
    visibility: 22600
    wind_gust_speed: 27.8
    wind_bearing: SW
    temperature: 3
    templow: -1
    dew_point: -1
    wind_speed: 13
    precipitation: 0.1
  - datetime: "2025-01-11T00:00:00Z"
    cloud_coverage: 79
    condition: cloudy
    evaporation: null
    fog_probability: 4
    precipitation_duration: 8760
    precipitation_probability: 27
    pressure: 1030.6
    sun_duration: 8160
    sun_irradiance: 2630
    uv_index: null
    visibility: 13500
    wind_gust_speed: 20.4
    wind_bearing: W
    temperature: 2
    templow: -2
    dew_point: -3
    wind_speed: 11.1
    precipitation: 0
  - datetime: "2025-01-12T00:00:00Z"
    cloud_coverage: 75
    condition: cloudy
    evaporation: null
    fog_probability: 5
    precipitation_duration: 13980
    precipitation_probability: 36
    pressure: 1037.1
    sun_duration: 6720
    sun_irradiance: 2790
    uv_index: null
    visibility: 12100
    wind_gust_speed: 18.5
    wind_bearing: SW
    temperature: 1
    templow: -2
    dew_point: -4
    wind_speed: 11.1
    precipitation: 0
  - datetime: "2025-01-13T00:00:00Z"
    cloud_coverage: 69
    condition: cloudy
    evaporation: null
    fog_probability: 6
    precipitation_duration: 8400
    precipitation_probability: 27
    pressure: 1037.2
    sun_duration: 12960
    sun_irradiance: 3070
    uv_index: null
    visibility: 10400
    wind_gust_speed: 16.7
    wind_bearing: O
    temperature: 2
    templow: -4
    dew_point: -3
    wind_speed: 9.3
    precipitation: 0
  - datetime: "2025-01-14T00:00:00Z"
    cloud_coverage: 73
    condition: cloudy
    evaporation: null
    fog_probability: 6
    precipitation_duration: 7440
    precipitation_probability: 19
    pressure: 1033.7
    sun_duration: 11880
    sun_irradiance: 3180
    uv_index: null
    visibility: 9000
    wind_gust_speed: 14.8
    wind_bearing: O
    temperature: 2
    templow: -3
    dew_point: -2
    wind_speed: 9.3
    precipitation: 0
friendly_name: Weather Forecast Daily

```
